version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z-cpuv1
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "512M"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio/data:/data
    ports:
      - "9000:9000" # MinIO S3 API 端口
      - "9001:9001" # MinIO Web 控制台端口
    command: server /data --console-address ":9001"

#  software-api:
#    image: software-api:1.0
#    deploy:
#      replicas: 1
#    volumes:
#      - minio-data:/data
#    ports:
#      - "8000:8000"
#
#  software-front:
#    image: software-front:1.0
#    deploy:
#      replicas: 1
#    ports:
#      - "8080:80"

volumes:
  minio-data: